name: cubegen
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - segmentation-models-pytorch
  - sen2nbar
  - spyndex
  - utm
  - xcube >=1.11.0
  - xcube-cds >=0.9.3
  - xcube-stac >=1.1.0
  - zappend
